<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ── Roles ──────────────────────────────────────────────────────────────
        Role::firstOrCreate(['name' => 'admin',  'guard_name' => 'web']);
        Role::firstOrCreate(['name' => 'ibrahim',  'guard_name' => 'web']);
        Role::firstOrCreate(['name' => 'editor', 'guard_name' => 'web']);
        Role::firstOrCreate(['name' => 'user',   'guard_name' => 'web']);

        // ── Users ──────────────────────────────────────────────────────────────
        $admin = User::firstOrCreate(
            ['email' => 'ibrahim@gmail.com'],
            [
                'name'              => 'ibrahim',
                'password'          => Hash::make('ibrahim123456'),
                'email_verified_at' => now(),
            ]
        );
        $admin->syncRoles(['admin']);

        $editor = User::firstOrCreate(
            ['email' => 'editor@gmail.com'],
            [
                'name'              => 'Sara Hassan',
                'password'          => Hash::make('editor123456'),
                'email_verified_at' => now(),
            ]
        );
        $editor->syncRoles(['editor']);

        $user = User::firstOrCreate(
            ['email' => 'user@gmail.com'],
            [
                'name'              => 'Mohamed Ali',
                'password'          => Hash::make('user123456'),
                'email_verified_at' => now(),
            ]
        );
        $user->syncRoles(['user']);

        // ── Categories ─────────────────────────────────────────────────────────
        $categoryData = [
            ['name' => 'Politics',      'slug' => 'politics',      'color' => '#1a1a2e', 'order' => 1],
            ['name' => 'Sports',        'slug' => 'sports',        'color' => '#16213e', 'order' => 2],
            ['name' => 'Technology',    'slug' => 'technology',    'color' => '#0f3460', 'order' => 3],
            ['name' => 'Business',      'slug' => 'business',      'color' => '#533483', 'order' => 4],
            ['name' => 'Entertainment', 'slug' => 'entertainment', 'color' => '#e94560', 'order' => 5],
            ['name' => 'Health',        'slug' => 'health',        'color' => '#05c46b', 'order' => 6],
            ['name' => 'Science',       'slug' => 'science',       'color' => '#0fbcf9', 'order' => 7],
            ['name' => 'World News',    'slug' => 'world-news',    'color' => '#bb0011', 'order' => 8],
            ['name' => 'Local News',    'slug' => 'local-news',    'color' => '#f8b739', 'order' => 9],
        ];

        foreach ($categoryData as $cat) {
            Category::firstOrCreate(
                ['slug' => $cat['slug']],
                array_merge($cat, ['is_active' => true])
            );
        }

        // ── Articles ───────────────────────────────────────────────────────────
        $articles = $this->getArticles();
        $seeded   = 0;

        foreach ($articles as $articleData) {
            $categorySlug = $articleData['category_slug'];
            unset($articleData['category_slug']);

            $category = Category::where('slug', $categorySlug)->first();
            if (! $category) {
                continue;
            }

            $slug = Str::slug($articleData['title']);

            // Skip duplicates so re-seeding is safe
            if (Article::where('slug', $slug)->exists()) {
                continue;
            }

            Article::create([
                ...$articleData,
                'slug'         => $slug,
                'category_id'  => $category->id,
                'author_id'    => $admin->id,
                'status'       => 'published',
                'read_time'    => rand(3, 10),
                'published_at' => now()->subDays(rand(1, 45))->subHours(rand(0, 23)),
            ]);

            $seeded++;
        }
    }

    // ── All article data ───────────────────────────────────────────────────────

    private function getArticles(): array
    {
        return [

            // ══════════════════════════════════════════════════════════════════
            //  WORLD NEWS  (30 articles)
            // ══════════════════════════════════════════════════════════════════

            [
                'title'          => 'US-Iran Tensions Escalate Following Military Strikes',
                'subtitle'       => 'Global leaders call for restraint as fears of wider regional conflict grow',
                'excerpt'        => 'Tensions between the United States and Iran intensified following a series of military strikes, prompting urgent diplomatic efforts.',
                'content'        => '<h2>Rising Regional Tensions</h2><p>International attention remains focused on the Middle East following recent military developments.</p><p>World leaders urged restraint while diplomatic efforts continue.</p><h2>Global Response</h2><p>Energy markets reacted sharply amid concerns over regional stability.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['usa', 'iran', 'middle-east', 'world'],
                'views_count'    => 45800,
                'featured_image' => 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'UN Calls Emergency Meeting Over Regional Conflict',
                'subtitle'       => 'Security Council members seek diplomatic solutions',
                'excerpt'        => 'The United Nations has convened an emergency meeting to address growing concerns over regional instability.',
                'content'        => '<h2>Emergency Session</h2><p>UN officials gathered to discuss recent developments affecting international security.</p><p>Member states emphasized diplomacy and conflict prevention.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['un', 'diplomacy', 'security', 'world'],
                'views_count'    => 32100,
                'featured_image' => 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'European Leaders Discuss New Security Measures',
                'subtitle'       => 'Summit focuses on defense cooperation and stability',
                'excerpt'        => 'European leaders met to discuss strengthening regional security and defense partnerships.',
                'content'        => '<h2>Security Summit</h2><p>Officials reviewed emerging threats and regional challenges.</p><p>Several proposals for enhanced cooperation were introduced.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['europe', 'security', 'politics', 'world'],
                'views_count'    => 27600,
                'featured_image' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'China Expands Global Trade Partnerships',
                'subtitle'       => 'New agreements strengthen economic ties across continents',
                'excerpt'        => 'China announced several new trade partnerships aimed at boosting international commerce.',
                'content'        => '<h2>Trade Expansion</h2><p>Economic officials highlighted new opportunities for investment and infrastructure development.</p><p>Analysts expect stronger trade volumes over the coming years.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['china', 'trade', 'economy', 'world'],
                'views_count'    => 29100,
                'featured_image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Middle East Peace Talks Resume in Geneva',
                'subtitle'       => 'Diplomatic representatives return to negotiation table',
                'excerpt'        => 'Peace talks resumed in Geneva as negotiators seek long-term regional stability.',
                'content'        => '<h2>Negotiations Continue</h2><p>Delegations from multiple countries resumed discussions under international supervision.</p><p>Observers remain cautiously optimistic.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['peace', 'geneva', 'middle-east', 'world'],
                'views_count'    => 41300,
                'featured_image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'NATO Announces Joint Military Exercises',
                'subtitle'       => 'Member nations coordinate large-scale training operations',
                'excerpt'        => 'NATO has announced new military exercises involving thousands of personnel.',
                'content'        => '<h2>Joint Operations</h2><p>The exercises aim to improve readiness and coordination among allied forces.</p><p>Officials described the drills as defensive in nature.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['nato', 'military', 'defense', 'world'],
                'views_count'    => 33700,
                'featured_image' => 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Global Leaders Meet for Climate Summit',
                'subtitle'       => 'New environmental commitments announced',
                'excerpt'        => 'World leaders gathered to discuss climate change and sustainable development goals.',
                'content'        => '<h2>Climate Action</h2><p>Participants outlined strategies to reduce emissions and accelerate renewable energy adoption.</p><p>Several nations announced ambitious targets.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['climate', 'environment', 'summit', 'world'],
                'views_count'    => 28900,
                'featured_image' => 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'New Sanctions Impact International Markets',
                'subtitle'       => 'Investors monitor economic consequences',
                'excerpt'        => 'Fresh sanctions have triggered reactions across global financial markets.',
                'content'        => '<h2>Market Reaction</h2><p>Analysts reported increased volatility in several sectors.</p><p>Governments continue evaluating the long-term impact.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['sanctions', 'markets', 'economy', 'world'],
                'views_count'    => 35200,
                'featured_image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Refugee Crisis Prompts International Response',
                'subtitle'       => 'Aid organizations expand support efforts',
                'excerpt'        => 'Humanitarian agencies are increasing assistance for displaced populations.',
                'content'        => '<h2>Humanitarian Support</h2><p>International organizations have mobilized resources to assist affected communities.</p><p>Relief operations are ongoing.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['refugees', 'humanitarian', 'aid', 'world'],
                'views_count'    => 24700,
                'featured_image' => 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Diplomatic Talks Aim to Reduce Border Tensions',
                'subtitle'       => 'Neighboring countries seek peaceful solutions',
                'excerpt'        => 'Diplomatic negotiations continue as leaders work to reduce tensions along disputed borders.',
                'content'        => '<h2>Peace Efforts</h2><p>Officials held several rounds of talks focused on stability and cooperation.</p><p>Additional meetings are expected in the coming weeks.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['diplomacy', 'borders', 'peace', 'world'],
                'views_count'    => 23100,
                'featured_image' => 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'African Union Launches New Development Initiative',
                'subtitle'       => 'Program aims to accelerate economic growth across member states',
                'excerpt'        => 'The African Union unveiled a new initiative focused on infrastructure, trade, and sustainable development.',
                'content'        => '<h2>Continental Growth</h2><p>African leaders endorsed a long-term strategy to improve connectivity and economic cooperation.</p><p>The initiative is expected to attract significant investment.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['africa', 'development', 'economy', 'world'],
                'views_count'    => 28400,
                'featured_image' => 'https://images.unsplash.com/photo-1489493887464-892be6d1daae?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Major Cyberattack Targets Government Systems',
                'subtitle'       => 'Authorities investigate large-scale digital breach',
                'excerpt'        => 'Several government networks were affected by a sophisticated cyberattack.',
                'content'        => '<h2>Cybersecurity Alert</h2><p>Investigators are working to determine the source and scope of the incident.</p><p>Security measures have been strengthened across affected systems.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['cybersecurity', 'technology', 'government', 'world'],
                'views_count'    => 42900,
                'featured_image' => 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'International Court Issues Landmark Ruling',
                'subtitle'       => 'Decision expected to influence future legal disputes',
                'excerpt'        => 'A landmark ruling by an international court has drawn worldwide attention.',
                'content'        => '<h2>Historic Decision</h2><p>Legal experts say the judgment could shape future international law cases.</p><p>Governments are reviewing the implications.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['court', 'law', 'justice', 'world'],
                'views_count'    => 21800,
                'featured_image' => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'World Leaders Push for Energy Cooperation',
                'subtitle'       => 'Summit focuses on long-term energy security',
                'excerpt'        => 'Global leaders are seeking stronger partnerships to secure future energy supplies.',
                'content'        => '<h2>Energy Security</h2><p>Officials discussed strategies to balance demand, sustainability, and affordability.</p><p>New agreements are expected in the coming months.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['energy', 'cooperation', 'economy', 'world'],
                'views_count'    => 26700,
                'featured_image' => 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Global Food Security Concerns Grow',
                'subtitle'       => 'Experts warn of supply chain challenges',
                'excerpt'        => 'Food security remains a major concern as countries face rising demand and climate pressures.',
                'content'        => '<h2>Food Supply Challenges</h2><p>Organizations are working to strengthen agricultural resilience and trade networks.</p><p>International cooperation remains essential.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['food', 'agriculture', 'economy', 'world'],
                'views_count'    => 24500,
                'featured_image' => 'https://images.unsplash.com/photo-1506617420156-8e4536971650?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Historic Peace Agreement Signed',
                'subtitle'       => 'Negotiators reach breakthrough after years of talks',
                'excerpt'        => 'A historic peace agreement has been signed, ending years of political tensions.',
                'content'        => '<h2>Breakthrough Achievement</h2><p>Leaders celebrated the agreement as a major step toward lasting stability.</p><p>Implementation efforts will begin immediately.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['peace', 'agreement', 'diplomacy', 'world'],
                'views_count'    => 49200,
                'featured_image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Oil Prices Rise Amid Regional Uncertainty',
                'subtitle'       => 'Markets react to geopolitical developments',
                'excerpt'        => 'Global oil prices increased as investors monitored regional developments.',
                'content'        => '<h2>Market Impact</h2><p>Energy traders reacted to uncertainty surrounding supply routes and production levels.</p><p>Analysts expect continued volatility.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['oil', 'markets', 'energy', 'world'],
                'views_count'    => 37600,
                'featured_image' => 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Nuclear Negotiations Continue in Europe',
                'subtitle'       => 'Diplomats seek progress on key issues',
                'excerpt'        => 'International negotiators remain engaged in discussions over nuclear agreements.',
                'content'        => '<h2>Ongoing Talks</h2><p>Representatives met for another round of negotiations.</p><p>Observers say progress has been made on several issues.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['nuclear', 'europe', 'diplomacy', 'world'],
                'views_count'    => 22400,
                'featured_image' => 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5ce?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'UN Peacekeeping Mission Expanded',
                'subtitle'       => 'Additional personnel deployed to support stability',
                'excerpt'        => 'The United Nations announced an expansion of a major peacekeeping operation.',
                'content'        => '<h2>Peacekeeping Efforts</h2><p>Additional resources have been allocated to support security and humanitarian objectives.</p><p>The mission will operate under an expanded mandate.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['un', 'peacekeeping', 'security', 'world'],
                'views_count'    => 21300,
                'featured_image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'International Aid Arrives in Disaster Zone',
                'subtitle'       => 'Relief teams coordinate emergency response efforts',
                'excerpt'        => 'International aid organizations have delivered supplies to affected communities.',
                'content'        => '<h2>Emergency Relief</h2><p>Food, medicine, and shelter materials are being distributed to those in need.</p><p>Recovery efforts remain ongoing.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['aid', 'humanitarian', 'disaster', 'world'],
                'views_count'    => 34500,
                'featured_image' => 'https://images.unsplash.com/photo-1469571486292-b53601020f52?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Cross-Border Trade Reaches New High',
                'subtitle'       => 'International commerce records strongest growth in years',
                'excerpt'        => 'Global trade volumes have reached a record high as economic activity accelerates across major markets.',
                'content'        => '<h2>Trade Expansion</h2><p>New data shows international trade activity continues to grow despite ongoing economic challenges.</p><p>Experts believe stronger supply chains and investment flows are supporting the trend.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['trade', 'economy', 'global', 'world'],
                'views_count'    => 28700,
                'featured_image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Nations Agree on New Maritime Treaty',
                'subtitle'       => 'Agreement aims to improve international cooperation at sea',
                'excerpt'        => 'Several nations have signed a maritime treaty designed to strengthen navigation and security standards.',
                'content'        => '<h2>Maritime Cooperation</h2><p>The agreement establishes new frameworks for cooperation and dispute resolution.</p><p>Officials described it as a milestone for international relations.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['maritime', 'treaty', 'international', 'world'],
                'views_count'    => 22100,
                'featured_image' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Defense Ministers Meet for Security Summit',
                'subtitle'       => 'Regional stability and cooperation top agenda',
                'excerpt'        => 'Defense ministers from several countries met to discuss shared security concerns.',
                'content'        => '<h2>Security Discussions</h2><p>Officials exchanged views on defense cooperation and emerging threats.</p><p>Future meetings are expected later this year.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['defense', 'security', 'summit', 'world'],
                'views_count'    => 25800,
                'featured_image' => 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Humanitarian Organizations Increase Support',
                'subtitle'       => 'Aid groups expand operations in vulnerable regions',
                'excerpt'        => 'International humanitarian organizations have increased support for communities facing hardship.',
                'content'        => '<h2>Growing Assistance</h2><p>Relief agencies are scaling up programs to address urgent needs.</p><p>Additional funding has been pledged by international donors.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['aid', 'humanitarian', 'support', 'world'],
                'views_count'    => 33200,
                'featured_image' => 'https://images.unsplash.com/photo-1469571486292-b53601020f52?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Global Migration Trends Under Review',
                'subtitle'       => 'Experts examine long-term population movements',
                'excerpt'        => 'Researchers are analyzing migration patterns and their impact on economies worldwide.',
                'content'        => '<h2>Migration Analysis</h2><p>New reports highlight changing migration trends across multiple regions.</p><p>Governments are reviewing policy responses.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['migration', 'population', 'research', 'world'],
                'views_count'    => 21400,
                'featured_image' => 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'International Election Observers Deployed',
                'subtitle'       => 'Teams monitor voting process in key elections',
                'excerpt'        => 'Election observers have been deployed to ensure transparency and fairness during voting.',
                'content'        => '<h2>Election Monitoring</h2><p>International observers are working alongside local authorities.</p><p>Preliminary reports indicate a smooth process.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['elections', 'democracy', 'politics', 'world'],
                'views_count'    => 24600,
                'featured_image' => 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Economic Cooperation Talks Advance',
                'subtitle'       => 'Negotiators report progress on trade and investment issues',
                'excerpt'        => 'Countries participating in economic cooperation talks reported significant progress.',
                'content'        => '<h2>Economic Dialogue</h2><p>Officials discussed trade, infrastructure, and investment opportunities.</p><p>Further agreements may be announced soon.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['economy', 'trade', 'investment', 'world'],
                'views_count'    => 30100,
                'featured_image' => 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Regional Alliance Announces New Strategy',
                'subtitle'       => 'Leaders unveil roadmap for future cooperation',
                'excerpt'        => 'A regional alliance has introduced a new strategy focused on security and development.',
                'content'        => '<h2>Strategic Vision</h2><p>Member states approved initiatives designed to strengthen cooperation.</p><p>The strategy outlines goals for the next decade.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['alliance', 'strategy', 'cooperation', 'world'],
                'views_count'    => 23500,
                'featured_image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Global Infrastructure Projects Gain Momentum',
                'subtitle'       => 'Major investments support transportation and energy networks',
                'excerpt'        => 'Infrastructure projects worldwide are accelerating as governments invest in modernization.',
                'content'        => '<h2>Infrastructure Growth</h2><p>New projects are expected to improve connectivity and economic efficiency.</p><p>Investors remain optimistic about long-term benefits.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['infrastructure', 'investment', 'development', 'world'],
                'views_count'    => 31800,
                'featured_image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'World Leaders Address Emerging Challenges',
                'subtitle'       => 'Forum highlights technology, security, and sustainability',
                'excerpt'        => 'Global leaders gathered to discuss the challenges shaping the future of international relations.',
                'content'        => '<h2>Global Priorities</h2><p>Discussions focused on technology, climate, security, and economic resilience.</p><p>Participants emphasized international cooperation as a key solution.</p>',
                'category_slug'  => 'world-news',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['leaders', 'global', 'politics', 'world'],
                'views_count'    => 40100,
                'featured_image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop',
            ],

            // ══════════════════════════════════════════════════════════════════
            //  SPORTS  (10 articles)
            // ══════════════════════════════════════════════════════════════════

            [
                'title'          => 'FIFA World Cup Delivers Thrilling Upset',
                'subtitle'       => 'Underdog nation shocks tournament favorites',
                'excerpt'        => 'One of the biggest surprises in World Cup history unfolded as an underdog team defeated a tournament favorite.',
                'content'        => '<h2>Historic Upset</h2><p>Fans witnessed a dramatic result as the underdogs secured a memorable victory.</p><p>The win has reshaped expectations for the remainder of the tournament.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['football', 'world-cup', 'sports'],
                'views_count'    => 52400,
                'featured_image' => 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Egypt Eyes Strong World Cup Campaign',
                'subtitle'       => 'Coaching staff confident ahead of qualifiers',
                'excerpt'        => 'Egypt is preparing for an important World Cup qualification campaign with renewed optimism.',
                'content'        => '<h2>Road To Qualification</h2><p>The national team has intensified preparations ahead of crucial matches.</p><p>Supporters remain hopeful for a successful campaign.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['egypt', 'football', 'world-cup'],
                'views_count'    => 41800,
                'featured_image' => 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Champions League Final Breaks Viewership Records',
                'subtitle'       => 'Millions tune in to watch European football showdown',
                'excerpt'        => 'The Champions League final attracted record audiences across global broadcasting platforms.',
                'content'        => '<h2>Record Audience</h2><p>The final generated massive engagement worldwide.</p><p>Broadcasters reported historic viewing figures.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['champions-league', 'football', 'sports'],
                'views_count'    => 46700,
                'featured_image' => 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Premier League Title Race Intensifies',
                'subtitle'       => 'Top clubs separated by only a few points',
                'excerpt'        => 'The battle for the Premier League title continues to captivate football fans worldwide.',
                'content'        => '<h2>Title Challenge</h2><p>Several clubs remain in contention for the championship.</p><p>The race is expected to continue until the final matchday.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['premier-league', 'football', 'sports'],
                'views_count'    => 39500,
                'featured_image' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Star Striker Leads Team to Victory',
                'subtitle'       => 'Match-winning performance secures important points',
                'excerpt'        => 'A star striker delivered an outstanding display to guide his team to victory.',
                'content'        => '<h2>Match Hero</h2><p>The player scored crucial goals and created several chances.</p><p>Fans celebrated another memorable performance.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['football', 'sports', 'player'],
                'views_count'    => 34100,
                'featured_image' => 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Historic Comeback Stuns Football Fans',
                'subtitle'       => 'Team overturns huge deficit in dramatic fashion',
                'excerpt'        => 'Supporters witnessed an unforgettable comeback during a thrilling football encounter.',
                'content'        => '<h2>Incredible Turnaround</h2><p>The team recovered from a difficult position to secure victory.</p><p>Analysts described the result as one of the season\'s best stories.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['football', 'comeback', 'sports'],
                'views_count'    => 48600,
                'featured_image' => 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Olympic Preparations Enter Final Stage',
                'subtitle'       => 'Host city completes key infrastructure projects',
                'excerpt'        => 'Preparations for the upcoming Olympic Games have entered their final phase.',
                'content'        => '<h2>Olympic Countdown</h2><p>Organizers reported strong progress across venues and logistics.</p><p>Millions of visitors are expected to attend.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['olympics', 'sports'],
                'views_count'    => 26800,
                'featured_image' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Tennis Champion Claims Grand Slam Title',
                'subtitle'       => 'Victory cements place among sport\'s elite',
                'excerpt'        => 'A dominant performance secured another Grand Slam trophy for the world-renowned champion.',
                'content'        => '<h2>Grand Slam Success</h2><p>The champion controlled the match from start to finish.</p><p>The victory adds another major title to an impressive career.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['tennis', 'grand-slam', 'sports'],
                'views_count'    => 31200,
                'featured_image' => 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Basketball Finals Reach Decisive Game',
                'subtitle'       => 'Championship series set for dramatic conclusion',
                'excerpt'        => 'The basketball finals will be decided in a winner-takes-all showdown.',
                'content'        => '<h2>Championship Decider</h2><p>Both teams have delivered exceptional performances throughout the series.</p><p>Fans eagerly await the final game.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['basketball', 'finals', 'sports'],
                'views_count'    => 29700,
                'featured_image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'New Record Set at International Marathon',
                'subtitle'       => 'Elite runners produce historic performances',
                'excerpt'        => 'A new course record was established during a major international marathon event.',
                'content'        => '<h2>Historic Achievement</h2><p>Thousands participated while elite athletes delivered remarkable results.</p><p>The new record highlights the growing standard of competition.</p>',
                'category_slug'  => 'sports',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['marathon', 'athletics', 'sports'],
                'views_count'    => 28300,
                'featured_image' => 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&auto=format&fit=crop',
            ],

            // ══════════════════════════════════════════════════════════════════
            //  TECHNOLOGY  (5 articles)
            // ══════════════════════════════════════════════════════════════════

            [
                'title'          => 'AI Investments Reach Record Levels',
                'subtitle'       => 'Global funding for artificial intelligence startups surges',
                'excerpt'        => 'Investments in artificial intelligence companies have reached record highs as businesses race to adopt AI-powered solutions across industries.',
                'content'        => '<h2>AI Investment Boom</h2><p>Global investors have poured billions of dollars into artificial intelligence startups over the past year, making AI one of the fastest-growing technology sectors worldwide.</p><p>Major technology firms and venture capital groups continue to compete for opportunities in generative AI, automation, and machine learning.</p><h2>Future Outlook</h2><p>Experts expect investment activity to remain strong as companies increasingly integrate AI tools into everyday operations.</p>',
                'category_slug'  => 'technology',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['ai', 'technology', 'investment', 'innovation'],
                'views_count'    => 25480,
                'featured_image' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'New Robotics Breakthrough Announced',
                'subtitle'       => 'Researchers unveil advanced autonomous systems',
                'excerpt'        => 'Scientists have introduced a new generation of robots capable of performing complex tasks with greater accuracy and efficiency.',
                'content'        => '<h2>Robotics Innovation</h2><p>A team of engineers has announced a breakthrough in robotics technology, allowing machines to perform detailed operations with minimal human intervention.</p><p>The innovation is expected to improve manufacturing, healthcare, and logistics industries.</p><h2>Industry Impact</h2><p>Experts believe the technology could significantly boost productivity while reducing operational costs.</p>',
                'category_slug'  => 'technology',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['robotics', 'automation', 'technology'],
                'views_count'    => 18340,
                'featured_image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Cybersecurity Firms Warn of Rising Threats',
                'subtitle'       => 'Organizations urged to strengthen digital defenses',
                'excerpt'        => 'Cybersecurity experts have warned of increasing cyberattacks targeting businesses and government institutions worldwide.',
                'content'        => '<h2>Growing Risks</h2><p>Security analysts report a significant rise in ransomware and phishing campaigns over the past year.</p><p>Organizations are being encouraged to implement stronger security measures and employee awareness programs.</p><h2>Protective Measures</h2><p>Experts recommend regular software updates, multi-factor authentication, and continuous monitoring.</p>',
                'category_slug'  => 'technology',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['cybersecurity', 'technology', 'security'],
                'views_count'    => 14790,
                'featured_image' => 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Tech Giants Expand Cloud Infrastructure',
                'subtitle'       => 'Major providers invest in new data centers',
                'excerpt'        => 'Leading technology companies are expanding cloud infrastructure to meet growing demand for digital services.',
                'content'        => '<h2>Cloud Growth</h2><p>Technology firms have announced major investments in data centers and cloud infrastructure projects around the world.</p><p>The expansion is expected to support AI workloads, enterprise software, and digital transformation initiatives.</p><h2>Market Demand</h2><p>Demand for scalable computing resources continues to rise across industries.</p>',
                'category_slug'  => 'technology',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['cloud', 'technology', 'data-centers'],
                'views_count'    => 16200,
                'featured_image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Researchers Develop Advanced AI Model',
                'subtitle'       => 'New system demonstrates improved reasoning abilities',
                'excerpt'        => 'A team of researchers has introduced an advanced AI model capable of handling more complex tasks with higher accuracy.',
                'content'        => '<h2>AI Research Progress</h2><p>The newly developed artificial intelligence model has demonstrated significant improvements in reasoning, language understanding, and problem-solving.</p><p>Researchers believe the technology could support applications in healthcare, education, and scientific discovery.</p><h2>Next Steps</h2><p>Further testing is planned before large-scale deployment begins.</p>',
                'category_slug'  => 'technology',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['ai', 'research', 'technology'],
                'views_count'    => 22870,
                'featured_image' => 'https://images.unsplash.com/photo-1675557009875-436f2fda4c22?w=800&auto=format&fit=crop',
            ],

            // ══════════════════════════════════════════════════════════════════
            //  BUSINESS  (5 articles)
            // ══════════════════════════════════════════════════════════════════

            [
                'title'          => 'Global Markets Rally on Economic Optimism',
                'subtitle'       => 'Investors respond positively to stronger growth forecasts',
                'excerpt'        => 'Global stock markets moved higher as investors reacted to encouraging economic data and improved growth expectations.',
                'content'        => '<h2>Market Momentum</h2><p>Major stock indices posted gains after new economic reports indicated stronger-than-expected growth across several key economies.</p><p>Investors welcomed positive corporate earnings and improving consumer confidence figures.</p><h2>Looking Ahead</h2><p>Analysts believe market sentiment could remain positive if economic conditions continue to improve.</p>',
                'category_slug'  => 'business',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['markets', 'economy', 'stocks', 'business'],
                'views_count'    => 21450,
                'featured_image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Oil Prices Stabilize After Volatile Week',
                'subtitle'       => 'Energy markets find balance following uncertainty',
                'excerpt'        => 'Oil prices stabilized after sharp fluctuations driven by geopolitical developments and supply concerns.',
                'content'        => '<h2>Energy Markets</h2><p>Crude oil prices steadied after a week of significant volatility in global energy markets.</p><p>Traders continue to monitor supply levels and geopolitical developments closely.</p><h2>Industry Outlook</h2><p>Analysts expect prices to remain sensitive to international events in the coming weeks.</p>',
                'category_slug'  => 'business',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['oil', 'energy', 'business', 'markets'],
                'views_count'    => 17820,
                'featured_image' => 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Major Bank Announces Expansion Strategy',
                'subtitle'       => 'New branches and digital services planned',
                'excerpt'        => 'One of the world\'s leading banks has unveiled an ambitious expansion plan focused on digital transformation and regional growth.',
                'content'        => '<h2>Expansion Plans</h2><p>The bank announced plans to open new branches while increasing investment in online banking services.</p><p>Executives say the strategy aims to improve customer access and accelerate innovation.</p><h2>Growth Targets</h2><p>The institution expects strong growth in both retail and corporate banking segments.</p>',
                'category_slug'  => 'business',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['banking', 'finance', 'business'],
                'views_count'    => 14230,
                'featured_image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'International Trade Volumes Increase',
                'subtitle'       => 'Global commerce shows signs of resilience',
                'excerpt'        => 'International trade activity has expanded as demand for goods and services continues to recover across multiple regions.',
                'content'        => '<h2>Trade Growth</h2><p>New figures show international trade volumes increasing despite ongoing economic uncertainties.</p><p>Export-driven economies recorded particularly strong performance during the latest quarter.</p><h2>Economic Impact</h2><p>Economists say stronger trade activity could support broader global growth.</p>',
                'category_slug'  => 'business',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['trade', 'economy', 'business'],
                'views_count'    => 15690,
                'featured_image' => 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Investors Focus on Emerging Markets',
                'subtitle'       => 'Capital flows increase toward developing economies',
                'excerpt'        => 'Investors are showing renewed interest in emerging markets as growth opportunities attract global capital.',
                'content'        => '<h2>Emerging Opportunities</h2><p>Investment funds have increased exposure to developing economies amid expectations of stronger long-term growth.</p><p>Several regions have reported rising foreign direct investment and expanding business activity.</p><h2>Future Trends</h2><p>Analysts expect emerging markets to remain a major focus for investors throughout the year.</p>',
                'category_slug'  => 'business',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['investment', 'markets', 'business', 'economy'],
                'views_count'    => 19340,
                'featured_image' => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=800&auto=format&fit=crop',
            ],

            // ══════════════════════════════════════════════════════════════════
            //  HEALTH  (5 articles)
            // ══════════════════════════════════════════════════════════════════

            [
                'title'          => 'WHO Launches New Global Health Initiative',
                'subtitle'       => 'Program aims to improve healthcare access worldwide',
                'excerpt'        => 'The World Health Organization has announced a new initiative designed to expand healthcare access and strengthen medical systems globally.',
                'content'        => '<h2>Global Health Effort</h2><p>The World Health Organization unveiled a comprehensive health initiative focused on improving access to medical services in underserved regions.</p><p>The program will support healthcare infrastructure, workforce training, and disease prevention efforts.</p><h2>Expected Impact</h2><p>Officials believe the initiative could improve healthcare outcomes for millions of people worldwide.</p>',
                'category_slug'  => 'health',
                'is_breaking'    => true,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['health', 'who', 'global-health', 'medicine'],
                'views_count'    => 21740,
                'featured_image' => 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Medical Researchers Announce Breakthrough',
                'subtitle'       => 'Scientists report promising new findings',
                'excerpt'        => 'Researchers have revealed a major medical breakthrough that could improve treatment options for patients worldwide.',
                'content'        => '<h2>Scientific Progress</h2><p>Medical researchers announced encouraging results from a new study that could lead to more effective treatment methods.</p><p>The findings are expected to influence future healthcare strategies and research efforts.</p><h2>Future Research</h2><p>Additional studies are planned to confirm the long-term benefits of the discovery.</p>',
                'category_slug'  => 'health',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => true,
                'tags'           => ['research', 'medicine', 'health'],
                'views_count'    => 18450,
                'featured_image' => 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'New Vaccine Program Expands Coverage',
                'subtitle'       => 'Public health agencies increase immunization efforts',
                'excerpt'        => 'Health authorities have launched an expanded vaccination campaign aimed at improving protection against preventable diseases.',
                'content'        => '<h2>Vaccination Campaign</h2><p>Healthcare agencies are expanding vaccine coverage through new outreach programs and awareness campaigns.</p><p>Officials say the effort will help reduce the spread of infectious diseases.</p><h2>Community Benefits</h2><p>Experts emphasize that increased vaccination rates contribute to stronger public health outcomes.</p>',
                'category_slug'  => 'health',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['vaccine', 'health', 'public-health'],
                'views_count'    => 16520,
                'featured_image' => 'https://images.unsplash.com/photo-1612277795421-9bc7706a4a41?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'Healthcare Technology Improves Patient Outcomes',
                'subtitle'       => 'Digital tools transform modern medical care',
                'excerpt'        => 'Healthcare providers are increasingly using digital technologies to improve patient care and clinical efficiency.',
                'content'        => '<h2>Digital Healthcare</h2><p>Hospitals and clinics are adopting advanced digital tools that help physicians make faster and more accurate decisions.</p><p>Technology is improving communication, diagnostics, and treatment planning.</p><h2>Industry Growth</h2><p>The healthcare technology sector continues to attract significant investment worldwide.</p>',
                'category_slug'  => 'health',
                'is_breaking'    => false,
                'is_featured'    => true,
                'is_trending'    => false,
                'tags'           => ['healthcare', 'technology', 'health'],
                'views_count'    => 15210,
                'featured_image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&auto=format&fit=crop',
            ],
            [
                'title'          => 'International Study Reveals Health Trends',
                'subtitle'       => 'Researchers identify key global healthcare patterns',
                'excerpt'        => 'A new international study has highlighted emerging health trends that could shape future healthcare policies.',
                'content'        => '<h2>Research Findings</h2><p>Scientists analyzed healthcare data from multiple countries to identify long-term health patterns and challenges.</p><p>The study highlights the importance of prevention, early detection, and healthcare accessibility.</p><h2>Policy Implications</h2><p>Health officials say the findings could guide future public health planning and investments.</p>',
                'category_slug'  => 'health',
                'is_breaking'    => false,
                'is_featured'    => false,
                'is_trending'    => true,
                'tags'           => ['health', 'research', 'study'],
                'views_count'    => 14870,
                'featured_image' => 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&auto=format&fit=crop',
            ],

        ];
    }
}
